name:  sockjs_client
version: 0.3.6
description:  A SockJS client in Dart
homepage: https://github.com/nelsonsilva/sockjs-dart-client
authors:
- Nelson Silva <nelson.silva@inevo.pt>
- SÃ©bastien Deleuze

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart2_constant: ^1.0.0
  logging: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
  build_test: ^2.0.0
  build_web_compilers: ^2.16.5
  test: ">=0.12.23+1 <2.0.0"
